name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
      - uses: actions/cache@v2
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Echo the message
        run: |
          echo 'Hello world guys!'
      - name: Install dependencies
        run: yarn install
      - name: unitaries test
        run: yarn run test
      - name: e2e test
        run: yarn run test:e2e:run
      - name: compile
        run: yarn run build
