name: CI Example
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci-message-and-linter:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: "yarn"
          node-version: "14.17.0"
      - name: Echo the message
        run: |
          echo '!Hello guys from CI in react with TS!'
      - name: Install dependencies
        run: yarn ci
      - name: Eslint verify rules
        run: yarn run lint

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: "yarn"
          node-version: "14.17.0"
      - name: Install dependencies
        run: yarn ci
      - name: compile
        run: yarn run build
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  test-unitary:
    needs: [ci-message-and-linter, build]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: "yarn"
          node-version: "14.17.0"
      - name: Install dependencies
        run: yarn ci
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: unitaries test
        run: yarn run test

  test-e2e:
    needs: [ci-message-and-linter, build]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: "yarn"
          node-version: "14.17.0"
      - name: Install dependencies
        run: yarn ci
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: e2e test
        uses: cypress-io/github-action@v2
        with:
          command: yarn run test:e2e:run
          start: yarn run start
          wait-on: http://localhost:3000
