name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
      - name: Echo the message
        run: |
          echo 'Hello world guys!'
      - name: install
        run: yarn ci
      - name: test
        run: yarn run test
      - name: test
        run: yarn run test:e2e:run
      - name: compile
        run: yarn run build
