name: CI Example Pipeline
on:
  workflow_dispatch:
    release:
      types: [created]
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  avoid_redundancy:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel Previous Redudant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  ci-message-and-linter:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: "yarn"
          node-version: "14.17.0"
      - name: Echo the message
        run: |
          echo 'Hello guys from CI!'
      - name: Install dependencies
        run: yarn install
      - name: Eslint verify rules
        run: yarn run lint

  snyk-monitor-clean-code-and-vulnerabilities:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: "yarn"
          node-version: "14.17.0"
      - name: Install dependencies
        run: yarn install
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: "yarn"
          node-version: "14.17.0"
      - name: Install dependencies
        run: yarn install
      - name: compile build
        run: yarn run build
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  test-unitaries:
    needs: [ci-message-and-linter, build]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: "yarn"
          node-version: "14.17.0"
      - name: Install dependencies
        run: yarn install
      - name: compile build
        run: yarn run build
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: unitaries test
        run: yarn run test

  tests-e2e:
    needs: [ci-message-and-linter, build]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: "yarn"
          node-version: "14.17.0"
      - name: Install dependencies
        run: yarn install
      - name: compile build
        run: yarn run build
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: e2e test
        uses: cypress-io/github-action@v2
        with:
          command: yarn run test:e2e:run
          start: yarn run start
          wait-on: http://localhost:3000

  deploy-heroku-cloud:
    needs: [test-unitaries, tests-e2e]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deploy to Heroku Cloud
        if: ${{ github.event_name == 'push' }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          #healthcheck: "https://${{secrets.HEROKU_SERVER}}.herokuapp.com/health"
          #checkstring: "ok"
          #rollbackonhealthcheckfailed: true
          #delay: 3
          #procfile: web: yarn start
          #branch: main

  deploy-ghpages-cloud:
    needs: [test-unitaries, tests-e2e]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: "yarn"
          node-version: "14.17.0"
      - name: Install Dependencies and Build
        run: |
          yarn install
          yarn run build
      - name: Deploy to GH-Pages Cloud
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          github_token: ${{ github.token }}
          branch: gh-pages
          folder: build

  #deploy-netlify-cloud:
  #  needs: [test-unitaries, tests-e2e]
  #  runs-on: ubuntu-20.04
  #  steps:
  #    - uses: actions/checkout@v2
  #     with:
  #       fetch-depth: 0
  #    - name: Deploy to Netlify Cloud
  #     if: ${{ github.event_name == 'push' }}
  #     uses: nwtgck/actions-netlify@v1.2
  #     with:
  #       production-branch: main
  #     env:
  #      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  #       NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
  #       timeout-minutes: 1
